{{- if .Values.backend.ingress.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "eu-jap-hack.fullname" . }}-backend
  labels:
    {{- include "eu-jap-hack.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    haproxy.org/server-ssl: "false"
    {{- if .Values.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.tls.clusterIssuer | quote }}
    haproxy.org/ssl-redirect: "true"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.backend.ingress.host }}
      secretName: {{ include "eu-jap-hack.fullname" . }}-backend-tls
  {{- end }}
  rules:
    - host: {{ .Values.backend.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "eu-jap-hack.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}
