apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eu-jap-hack.fullname" . }}-keycloak-realm
  labels:
    {{- include "eu-jap-hack.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
data:
  realm-export.json: |
    {{- .Files.Get "configs/keycloak/realm-export.json" | nindent 4 }}
