---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eu-jap-hack.fullname" . }}-waltid-wallet
  labels:
    {{- include "eu-jap-hack.labels" . | nindent 4 }}
    app.kubernetes.io/component: waltid-wallet-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.waltidWalletApi.service.port }}
      targetPort: 7001
      protocol: TCP
  selector:
    app.kubernetes.io/name: waltid-wallet-api
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eu-jap-hack.fullname" . }}-waltid-issuer
  labels:
    {{- include "eu-jap-hack.labels" . | nindent 4 }}
    app.kubernetes.io/component: waltid-issuer-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.waltidIssuerApi.service.port }}
      targetPort: 7002
      protocol: TCP
  selector:
    app.kubernetes.io/name: waltid-issuer-api
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eu-jap-hack.fullname" . }}-waltid-verifier
  labels:
    {{- include "eu-jap-hack.labels" . | nindent 4 }}
    app.kubernetes.io/component: waltid-verifier-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.waltidVerifierApi.service.port }}
      targetPort: 7003
      protocol: TCP
  selector:
    app.kubernetes.io/name: waltid-verifier-api
    app.kubernetes.io/instance: {{ .Release.Name }}
