apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edc-byd-motors
  namespace: argocd
  labels:
    tenant: byd-motors
    managed-by: edc-provisioning
spec:
  project: default
  source:
    repoURL: https://github.com/smartSenseSolutions/jap-eu-hack-2026
    targetRevision: HEAD
    path: edc/tx-edc-eleven
    helm:
      releaseName: edc-byd-motors
      valueFiles:
        - values.yaml
        - values-byd-motors.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: edc-byd-motors
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
