apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edc-hello34
  namespace: argocd
  labels:
    tenant: hello34
    managed-by: edc-provisioning
spec:
  project: default
  source:
    repoURL: https://github.com/smartSenseSolutions/jap-eu-hack-2026
    targetRevision: HEAD
    path: edc/tx-edc-eleven
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: VAULT_SECRET
          value: vault-secret
        - name: HELM_VALUES_FILE
          value: "values.yaml -f values-hello34.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: edc-hello34
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
