apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edc-smartsense-consulting-solution
  namespace: argocd
  labels:
    tenant: "smartsense-consulting-solution"
    managed-by: edc-provisioning
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/smartSenseSolutions/jap-eu-hack-2026.git
    targetRevision: HEAD
    path: edc/tx-edc-eleven
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: VAULT_SECRET
          value: vault-secret
        - name: HELM_VALUES_FILE
          value: "values.yaml -f values-smartsense-consulting-solution.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: edc-smartsense-consulting-solution
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
