apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edc-test-motors-2
  namespace: argocd
  labels:
    tenant: test-motors-2
    managed-by: edc-provisioning
spec:
  project: default
  source:
    repoURL: https://github.com/smartSenseSolutions/jap-eu-hack-2026
    targetRevision: HEAD
    path: edc/tx-edc-eleven
    helm:
      releaseName: edc-test-motors-2
      valueFiles:
        - values.yaml
        - values-test-motors-2.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: edc-test-motors-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
