/**
 * Seed data for the demo — ensures the app works from a fresh DB.
 * Cars, credentials, companies, and user wallet data.
 */

export const seedCredentials = [
  {
    id: 'cred-org-tata-001',
    type: 'OrgVC',
    issuerId: 'eu-dataspace',
    issuerName: 'EU APAC Dataspace',
    subjectId: 'company-tata-001',
    issuedAt: '2024-01-15T09:00:00.000Z',
    status: 'active',
    credentialSubject: {
      companyName: 'TATA Motors',
      companyDid: 'did:eu-dataspace:company-tata-001',
      registrationNumber: 'L28920MH1945PLC004520',
      vatId: 'IN-TATA-VAT-2024',
      eoriNumber: 'INEORI0012345',
      cin: 'L28920MH1945PLC004520',
      gstNumber: '27AAACT2727Q1ZW',
      country: 'India',
      city: 'Mumbai',
      address: 'Bombay House, 24 Homi Mody Street, Mumbai 400001',
      adminName: 'Ratan Tata',
      adminEmail: 'admin@tatamotors.com',
      incorporationDate: '1945-09-01T00:00:00.000Z',
    },
  },
  {
    id: 'cred-org-digit-001',
    type: 'OrgVC',
    issuerId: 'eu-dataspace',
    issuerName: 'EU APAC Dataspace',
    subjectId: 'company-digit-001',
    issuedAt: '2024-02-01T09:00:00.000Z',
    status: 'active',
    credentialSubject: {
      companyName: 'Digit Insurance',
      companyDid: 'did:eu-dataspace:company-digit-001',
      registrationNumber: 'U66000KA2016PTC126215',
      vatId: 'IN-DIGIT-VAT-2024',
      country: 'IN',
      city: 'Bengaluru',
      address: 'Embassy Tech Village, Outer Ring Road, Bengaluru 560103',
      adminName: 'Kamesh Goyal',
      adminEmail: 'admin@godigit.com',
      incorporationDate: '2016-09-20T00:00:00.000Z',
      insuranceLicense: 'IRDAI/HLT/2017/001',
      authorizedEUDistributor: true,
    },
  },
  {
    id: 'cred-self-mario-001',
    type: 'SelfVC',
    issuerId: 'smartsense-idp',
    issuerName: 'SmartSense Identity Provider',
    subjectId: 'mario-sanchez',
    issuedAt: '2024-01-10T10:00:00.000Z',
    expiresAt: '2027-01-10T10:00:00.000Z',
    status: 'active',
    credentialSubject: {
      name: 'Mario Sanchez',
      email: 'mario.sanchez@email.it',
      nationality: 'Italian',
      dateOfBirth: '1985-06-15',
      did: 'did:smartsense:mario-sanchez',
    },
  },
];

export const seedCompanies = [
  {
    id: 'company-tata-001',
    name: 'TATA Motors',
    vatId: 'IN-TATA-VAT-2024',
    eoriNumber: 'INEORI0012345',
    cin: 'L28920MH1945PLC004520',
    gstNumber: '27AAACT2727Q1ZW',
    country: 'India',
    city: 'Mumbai',
    address: 'Bombay House, 24 Homi Mody Street, Mumbai 400001',
    adminName: 'Ratan Tata',
    adminEmail: 'admin@tatamotors.com',
    did: 'did:eu-dataspace:company-tata-001',
    registeredAt: '2024-01-15T09:00:00.000Z',
    credentialId: 'cred-org-tata-001',
  },
  {
    id: 'company-digit-001',
    name: 'Digit Insurance',
    vatId: 'IN-DIGIT-VAT-2024',
    country: 'IN',
    city: 'Bengaluru',
    address: 'Embassy Tech Village, Outer Ring Road, Bengaluru 560103',
    adminName: 'Kamesh Goyal',
    adminEmail: 'admin@godigit.com',
    did: 'did:eu-dataspace:company-digit-001',
    registeredAt: '2024-02-01T09:00:00.000Z',
    credentialId: 'cred-org-digit-001',
  },
];

export const seedCars = [
  {
    id: 'car-nexon-ev-001',
    vin: 'TATA2024NEXONEV001',
    make: 'TATA',
    model: 'Nexon EV',
    year: 2024,
    variant: 'Max LR',
    color: 'Pristine White',
    price: 22500,
    status: 'available',
    mileage: 0,
    fuelType: 'Electric',
    transmission: 'Automatic',
    manufacturerCredentialId: 'cred-org-tata-001',
    dpp: {
      stateOfHealth: {
        batteryHealth: 100,
        batteryCapacity: '40.5 kWh',
        range: '437 km',
        lastInspectionDate: '2024-01-20T10:00:00.000Z',
      },
      damageHistory: {
        hasDamage: false,
        incidents: [],
      },
      serviceHistory: {
        services: [
          { date: '2024-01-20T10:00:00.000Z', type: 'Pre-delivery Inspection', dealer: 'TATA Motors Mumbai', mileage: 5 },
        ],
      },
      ownershipChain: {
        manufacturer: 'TATA Motors',
        manufacturingDate: '2024-01-10T00:00:00.000Z',
        manufacturingPlant: 'Pune Plant, Maharashtra',
        currentOwner: null,
      },
      manufacturerCredential: {
        credentialId: 'cred-org-tata-001',
        legalParticipantId: 'org-cred-tata-001',
        issuer: 'TATA Motors Limited',
        type: 'OrgVC',
        issuedAt: '2024-01-15T09:00:00.000Z',
        status: 'active',
      },
    },
  },
  {
    id: 'car-harrier-001',
    vin: 'TATA2024HARRIER001',
    make: 'TATA',
    model: 'Harrier',
    year: 2024,
    variant: 'Fearless Plus',
    color: 'Ash Grey',
    price: 28000,
    status: 'available',
    mileage: 0,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    manufacturerCredentialId: 'cred-org-tata-001',
    dpp: {
      stateOfHealth: {
        engineHealth: 100,
        lastInspectionDate: '2024-02-01T10:00:00.000Z',
      },
      damageHistory: { hasDamage: false, incidents: [] },
      serviceHistory: {
        services: [
          { date: '2024-02-01T10:00:00.000Z', type: 'Pre-delivery Inspection', dealer: 'TATA Motors Pune', mileage: 8 },
        ],
      },
      ownershipChain: {
        manufacturer: 'TATA Motors',
        manufacturingDate: '2024-01-25T00:00:00.000Z',
        manufacturingPlant: 'Pune Plant, Maharashtra',
        currentOwner: null,
      },
      manufacturerCredential: {
        credentialId: 'cred-org-tata-001',
        legalParticipantId: 'org-cred-tata-001',
        issuer: 'TATA Motors Limited',
        type: 'OrgVC',
        issuedAt: '2024-01-15T09:00:00.000Z',
        status: 'active',
      },
    },
  },
  {
    id: 'car-punch-ev-001',
    vin: 'TATA2024PUNCHEV001',
    make: 'TATA',
    model: 'Punch EV',
    year: 2024,
    variant: 'Adventure Long Range',
    color: 'Seaweed Green',
    price: 15500,
    status: 'available',
    mileage: 0,
    fuelType: 'Electric',
    transmission: 'Automatic',
    manufacturerCredentialId: 'cred-org-tata-001',
    dpp: {
      stateOfHealth: {
        batteryHealth: 100,
        batteryCapacity: '35 kWh',
        range: '421 km',
        lastInspectionDate: '2024-03-01T10:00:00.000Z',
      },
      damageHistory: { hasDamage: false, incidents: [] },
      serviceHistory: {
        services: [
          { date: '2024-03-01T10:00:00.000Z', type: 'Pre-delivery Inspection', dealer: 'TATA Motors Delhi', mileage: 3 },
        ],
      },
      ownershipChain: {
        manufacturer: 'TATA Motors',
        manufacturingDate: '2024-02-20T00:00:00.000Z',
        manufacturingPlant: 'Sanand Plant, Gujarat',
        currentOwner: null,
      },
      manufacturerCredential: {
        credentialId: 'cred-org-tata-001',
        legalParticipantId: 'org-cred-tata-001',
        issuer: 'TATA Motors Limited',
        type: 'OrgVC',
        issuedAt: '2024-01-15T09:00:00.000Z',
        status: 'active',
      },
    },
  },
  {
    id: 'car-safari-001',
    vin: 'TATA2024SAFARI0001',
    make: 'TATA',
    model: 'Safari',
    year: 2024,
    variant: 'Accomplished Plus',
    color: 'Cosmic Gold',
    price: 32000,
    status: 'available',
    mileage: 0,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    manufacturerCredentialId: 'cred-org-tata-001',
    dpp: {
      stateOfHealth: {
        engineHealth: 100,
        lastInspectionDate: '2024-02-15T10:00:00.000Z',
      },
      damageHistory: { hasDamage: false, incidents: [] },
      serviceHistory: {
        services: [
          { date: '2024-02-15T10:00:00.000Z', type: 'Pre-delivery Inspection', dealer: 'TATA Motors Chennai', mileage: 12 },
        ],
      },
      ownershipChain: {
        manufacturer: 'TATA Motors',
        manufacturingDate: '2024-02-01T00:00:00.000Z',
        manufacturingPlant: 'Pune Plant, Maharashtra',
        currentOwner: null,
      },
      manufacturerCredential: {
        credentialId: 'cred-org-tata-001',
        legalParticipantId: 'org-cred-tata-001',
        issuer: 'TATA Motors Limited',
        type: 'OrgVC',
        issuedAt: '2024-01-15T09:00:00.000Z',
        status: 'active',
      },
    },
  },
  {
    id: 'car-curvv-ev-001',
    vin: 'TATA2024CURVVEV001',
    make: 'TATA',
    model: 'Curvv EV',
    year: 2025,
    variant: 'Accomplished S',
    color: 'Virtual Sunrise',
    price: 26000,
    status: 'available',
    mileage: 0,
    fuelType: 'Electric',
    transmission: 'Automatic',
    manufacturerCredentialId: 'cred-org-tata-001',
    dpp: {
      stateOfHealth: {
        batteryHealth: 100,
        batteryCapacity: '55 kWh',
        range: '502 km',
        lastInspectionDate: '2025-01-10T10:00:00.000Z',
      },
      damageHistory: { hasDamage: false, incidents: [] },
      serviceHistory: {
        services: [
          { date: '2025-01-10T10:00:00.000Z', type: 'Pre-delivery Inspection', dealer: 'TATA Motors Bangalore', mileage: 6 },
        ],
      },
      ownershipChain: {
        manufacturer: 'TATA Motors',
        manufacturingDate: '2024-12-20T00:00:00.000Z',
        manufacturingPlant: 'Sanand Plant, Gujarat',
        currentOwner: null,
      },
      manufacturerCredential: {
        credentialId: 'cred-org-tata-001',
        legalParticipantId: 'org-cred-tata-001',
        issuer: 'TATA Motors Limited',
        type: 'OrgVC',
        issuedAt: '2024-01-15T09:00:00.000Z',
        status: 'active',
      },
    },
  },
];

export const seedWallet: Record<string, { credentialIds: string[] }> = {
  'mario-sanchez': { credentialIds: ['cred-self-mario-001'] },
};

/**
 * Seeded org_credentials — Gaia-X Legal Participant records for TATA Motors and Digit Insurance.
 * These are resolvable via /vc/:id and used as the `issuer` in OwnershipVC / InsuranceVC.
 */
export const seedOrgCredentials = [
  {
    id: 'org-cred-tata-001',
    companyId: 'company-tata-001',
    legalName: 'TATA Motors Limited',
    legalRegistrationNumber: {
      vatId: 'IN27AAACT2727Q1ZW',
      eoriNumber: 'IN987654321000',
      localId: 'L28920MH1945PLC004415',
      taxId: 'AAACT2727Q',
    },
    legalAddress: {
      streetAddress: 'Bombay House, 24 Homi Mody Street',
      locality: 'Mumbai',
      postalCode: '400001',
      countryCode: 'IN',
      countrySubdivisionCode: 'IN-MH',
    },
    headquartersAddress: {
      streetAddress: 'Bombay House, 24 Homi Mody Street',
      locality: 'Mumbai',
      postalCode: '400001',
      countryCode: 'IN',
      countrySubdivisionCode: 'IN-MH',
    },
    website: 'https://www.tatamotors.com',
    contactEmail: 'admin@tatamotors.com',
    did: 'did:web:participant.gxdch.io:tata-motors',
    validFrom: '2024-01-15T09:00:00.000Z',
    validUntil: '2027-01-15T09:00:00.000Z',
    verificationStatus: 'draft' as const,
    verificationAttempts: [],
    createdAt: '2024-01-15T09:00:00.000Z',
    updatedAt: '2024-01-15T09:00:00.000Z',
  },
  {
    id: 'org-cred-digit-001',
    companyId: 'company-digit-001',
    legalName: 'Go Digit General Insurance Limited',
    legalRegistrationNumber: {
      vatId: 'IN29AADCG1234R1ZN',
      localId: 'U66000KA2016PTC126215',
      taxId: 'AADCG1234R',
    },
    legalAddress: {
      streetAddress: 'Embassy Tech Village, Outer Ring Road',
      locality: 'Bengaluru',
      postalCode: '560103',
      countryCode: 'IN',
      countrySubdivisionCode: 'IN-KA',
    },
    headquartersAddress: {
      streetAddress: 'Embassy Tech Village, Outer Ring Road',
      locality: 'Bengaluru',
      postalCode: '560103',
      countryCode: 'IN',
      countrySubdivisionCode: 'IN-KA',
    },
    website: 'https://www.godigit.com',
    contactEmail: 'admin@godigit.com',
    did: 'did:web:participant.gxdch.io:digit-insurance',
    validFrom: '2024-02-01T09:00:00.000Z',
    validUntil: '2027-02-01T09:00:00.000Z',
    verificationStatus: 'draft' as const,
    verificationAttempts: [],
    createdAt: '2024-02-01T09:00:00.000Z',
    updatedAt: '2024-02-01T09:00:00.000Z',
  },
];
